openshift-pipelines/performance

- tools/capture-sign-finalizer-runs-stats.sh
Added new script `capture-sign-finalizer-runs-stats.sh` to extracts run stats for PipelineRuns and TaskRuns from *benchmark-output.json* into CSV files.
`capture-sign-finalizer-runs-stats.sh artifacts/benchmark-output.json`
The script takes only one argument which is the path to the 'benchmark-output.json' artifact.
It creates the below directory structure and stores the run stats into these CSV files.
```
.
└── sign-finalizers/
├── pipelineruns-sign-finalizer-stat.csv
└── taskruns-sign-finalizer-stat.csv
```
> SRVKP-4331: Add script to convert benchmark-output.json result into CSV

- ci-scripts/load-test.sh
As the _load-test.sh_ script is setting `set -o nounset`, this makes bash to throw errors for all unbound variables. So added default null value for WAIT_TIME flag.
> fixed issue with unbound local variable

- tools/runs-to-csv.sh
Added `.measurements.tekton_tekton_chains_controller_workqueue_depth.mean` to _runs-to-csv.sh_ script.
> Add workqueue depth metrics for chains in runs-to-csv.sh

- tools/benchmark.py
- tools/visualize-benchmark-stats.sh
This PR introduces the following change:
- Add **terminated** measurement in `benchmark-stats.csv` output for pipelineruns and taskruns. This measurement is calculated by looking up  *.metadata.deletionTimestamp* flag in the object event definition.
- Update *visualize-benchmark-stats.sh* to incorporate new header ordering from adding **terminated** stats.
> feat(SRVKP-4471): Added new stat for capturing terminated status in benchmark script

- tests/scaling-pipelines/scenario/common/lib.sh
- tests/scaling-pipelines/scenario/signing-tr-tekton-bigbang-tr-multi-steps/pipeline.yaml.j2
- tests/scaling-pipelines/scenario/signing-tr-tekton-bigbang-tr-multi-steps/setup.sh
- tools/create-pipeline-yaml.py
- tools/stats.sh
- Updated test template for **signing-tr-tekton-bigbang-tr-multi-steps** scenario to include *task_count* parameter which sets the number of taskruns for test pipelines.
- Fixes: Resolves an issue with test scripts when TEST_NAMESPACE is not configured to default value 1 explicitly.
> feat(SRVKP-4548): Update Jinja2 test template to support multi-task runs

- ci-scripts/setup-cluster.sh
- tests/scaling-pipelines/scenario/common/lib.sh
This change adds a small delay before checking for chains controller status.
> Add sleep timeout before checking chains status

- tests/scaling-pipelines/scenario/signing-tr-varying-concurrency/setup.sh
Fix for disabling chains if it's not enabled. Previously chains were getting enabled by default .
> Fix for disabling chains if is not getting enabled

- ci-scripts/setup-cluster.sh
Chains setup is handled across tests individually in its `setup.sh`. To keep consistency between the initialization, only pipelines will be enabled as part of the cluster setup while keeping the chains and pruner disabled.
> fix(SRVKP-5598): Disable chains during cluster setup

- README.md
- tests/scaling-pipelines/scenario/common/lib.sh
- tools/convert-benchmark-stats.py
- Tested with 1.15 version of OpenShift Pipelines on ClusterBot. Updated readme instruction for deploying the latest v1.15 release.
- Fixed issue where updating field name order in "benchmark-stats.csv" would impact `wait_for_prs_finished` method due to hard coding of column index for lookup. Now column field is calculated upfront based on the column header from the file.
> test(SRVKP-5600): Updated readme instruction for testing OpenShift 1.15 + fixed issue with benchmark_stats field change

- tools/benchmark.py
- tools/compare-TaskRun-Pod-creationTimestamp.py
**Problem**
It was observed that random test runs were failing when trying to calculate duration for pod creation with the script `tools/compare-TaskRun-Pod-creationTimestamp.py`.
The issue was caused due to conflicting names for PRs/TRs objects that were present across multiple namespaces.
**Changes to resolve the issue**
- `compare-TaskRun-Pod-creationTimestamp.py`: The script now uses a combination of **namespace** and **object name** to create a unique key to represent the PR/TR. 
- `benchmark.py`: One of the test artifacts _benchmark-output.json_ contains a mapping of PRs/TRs object and different state information. The name key used for creating the mapping will lead to same duplicate issue and end up overriding existing information for PRs/TRs objects. Similar fix has been applied …
> fix(SRVKP-5763): Random failures in capturing TaskRun-Pod-creationTimestamp metric

- tests/scaling-pipelines/scenario/git-resolver/.gitignore
- tests/scaling-pipelines/scenario/git-resolver/README.md
- tests/scaling-pipelines/scenario/git-resolver/pipeline.yaml.j2
- tests/scaling-pipelines/scenario/git-resolver/run.yaml
- tests/scaling-pipelines/scenario/git-resolver/setup.sh
- tests/scaling-pipelines/scenario/git-resolver/task.yaml
- tests/scaling-pipelines/scenario/git-resolver/task.yaml.j2
- tests/scaling-pipelines/scenario/git-resolver/task_for_git.yaml
- tests/scaling-pipelines/scenario/git-resolver/tierdown.sh
Created a new scenario for Git Resolver Performance Testing
Considered this [task](https://github.com/openshift-pipelines/performance/pull/45/files#diff-6943a23db6ef8787c36eb55d1c7376757228e1727d4f7ee16066852f2e5c0f4d) from git for testing
Based on the `TEST_RESOLVER_TYPE` params it'll resolve the tasks either from Git or local definitions
JIRA link : https://issues.redhat.com/browse/SRVKP-5867
> Created a new scenario for Git Resolver Performance Testing

- README.md
- ci-scripts/setup-cluster.sh
- config/cluster_read_config.yaml
- tools/benchmark.py
- tools/convert-benchmark-stats.py
- The PR adds support for installing Tekton Results (both downstream/upstream) on OpenShift cluster as part of performance testing cluster setup.
- Introduces the following new environment variables for the Tekton Results setup:
- **INSTALL_RESULTS**: Whether to install Tekton Results during the cluster setup. 
(Possible Values: true/false | Default: false)
- **DEPLOYMENT_TYPE_RESULTS**: Which instance of Tekton Results to install 
(Possible Values: upstream/downstream | Default: downstream)
- **DEPLOYMENT_RESULTS_UPSTREAM_VERSION**: Used when **DEPLOYMENT_TYPE_RESULTS** set to *upstream* and specifies which version of upstream Tekton Results to install in cluster. 
(Values based on official [release](https://github.com/tektoncd/results/releases) | Default: latest)
- Additionally, the PR …
> feat(SRVKP-6127): Add Installing and Monitoring of Tekton Results

- ci-scripts/collect-results.sh
- ci-scripts/setup-cluster.sh
- tests/scaling-pipelines/scenario/timebased-sign-pruner/.gitignore
- tests/scaling-pipelines/scenario/timebased-sign-pruner/README.md
- tests/scaling-pipelines/scenario/timebased-sign-pruner/pipeline.yaml.j2
- tests/scaling-pipelines/scenario/timebased-sign-pruner/run.yaml
- tests/scaling-pipelines/scenario/timebased-sign-pruner/setup.sh
- tests/scaling-pipelines/scenario/timebased-sign-pruner/tierdown.sh
The PR adds a new testing scenario for stress testing Tekton Controllers (Pipelines, Chains, Pruner, Results) by constant load of PRs/TRs with log generation.
The following environment variables are available for controlling timeouts:
- **TOTAL_TIMEOUT**: Total time for test execution (Default: 2 hours)
- **CHAINS_WAIT_TIME**: Wait period before enabling chains (Default: 10 mins)
- **PRUNER_WAIT_TIME**: Wait period before enabling pruner (Default: 10 mins)
The following environment variables are available for controlling the PR/TR payload size and log outputs:
- **TEST_BIGBANG_MULTI_STEP__TASK_COUNT**: Total number of tasks per Pipeline (Default: 5 tasks)
- **TEST_BIGBANG_MULTI_STEP__STEP_COUNT**: Total number of steps per Task (Default: 10 steps)
- …
> feat(SRVKP-6149): New test scenario for evaluating tekton results use-case

- README.md
- ci-scripts/setup-cluster.sh
This change enables us to  store logs in PVC or S3 based on the boolean  `STORE_LOGS_IN_S3`
> Configure S3 for stroing logs from Tekton Results 

- ci-scripts/setup-cluster.sh
- config/openssl.cnf
Fix for OpenSSL issue in CI, added config file, and parsing the content  instead of `-addext`
[https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_rele[…]sults-downstream-1-15-with-results-1hr/1844716596841418752](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51008/rehearse-51008-pull-ci-openshift-pipelines-performance-main-tekton-results-downstream-1-15-with-results-1hr/1844716596841418752)
JIRA : https://issues.redhat.com/browse/SRVKP-6626
> Fix for openssl -addext not found issue in CI

- .gitignore
- README.md
- ci-scripts/collect-results.sh
- ci-scripts/setup-cluster.sh
- config/cluster_read_config.yaml
- config/locust-k8s-operator.values.yaml
- tests/scaling-pipelines/scenario/common/lib.sh
- tests/scaling-pipelines/scenario/common/locust-test-template.yaml
- tests/scaling-pipelines/scenario/timebased-sign-pruner/.gitignore
- tests/scaling-pipelines/scenario/timebased-sign-pruner/README.md
- tests/scaling-pipelines/scenario/timebased-sign-pruner/locust/fetch-log.py
- tests/scaling-pipelines/scenario/timebased-sign-pruner/locust/fetch-records.py
- tests/scaling-pipelines/scenario/timebased-sign-pruner/setup.sh
- tests/scaling-pipelines/scenario/timebased-sign-pruner/tierdown.sh
- tools/runs-to-csv.sh
This PR adds support to run Locust API tests as part of Performance benchmarking. 
https://issues.redhat.com/browse/SRVKP-6575
- Installing Locust-Operator on Cluster during the Cluster Setup by setting `RUN_LOCUST=true`. This will install all the necessary operators and in-addition will enable service monitor to forward for locust metrics from locust test jobs into prometheus.
- Capture aggregated values of request latency for the test in output json files and raw monitoring collection.
- Updates test scenario `timebased-sign-pruner` to add locust test jobs (more info below).
The first part of the scenario evaluates the performances of TektonResults, Pipeline Controllers, Chains and Pruner by creating PR/TR workloads. In the second part of the scenario, we trigger locust API tests named …
> feat(SRVKP-6575): Locust Script Support

- ci-scripts/collect-results.sh
When using `-t` flag with `kubectl exe` in CI environment, the job fails to connect into the container in interactive mode and fails the CI run.
Removes `--tty` flag and uses only the `-i` flag to pass the command line arguments for taking pg_dump from postgres DB.
> fix(SRVKP-6791): Issue with DB dump in non-interactive kubectl exec mode

- ci-scripts/collect-results.sh
- ci-scripts/lib.sh
- tests/scaling-pipelines/scenario/timebased-sign-pruner/locust/fetch-log.py
- tests/scaling-pipelines/scenario/timebased-sign-pruner/locust/fetch-record.py
- Switched to custom format to take Postgres dump by using `--format=c` flag. Now the data is stored in compressed binary format and can be restored using `pg_restore` command.
- Add new methods that captures SQL results for Result and Record tables from Postgres. Result from Queries are stored in `benchmark-tekton.json` under `.ResultsDB.queries`.
- For the `/log` locust test scenario now we add a random shuffle in picking record entry from the list.
- Adds a validation check after `/log` locust testing to pass the scenario only if we have a 200 status code response with non-zero length payload size.
- To avoid mixing results from PipelineRun and TaskRun logs, now the record ID is only considered for a TaskRun object. Locust test for `/record` endpoint also follows the same lookup to …
> feat(SRVKP-6872,SRVKP-6869,SRVKP-6875): Improve ResultsAPI DB collect metrics

- config/cluster_read_library.yaml
Updates `pod_suffix_regex` to match names based on prefix match for both Deployment and StatefulSet pod names.
> feat(SRVKP-6576): update pod_suffix_regex in cluster_ready_library

- config/cluster_read_config.yaml
This PR adds new Loki & Log collector metrics in `cluster_read_config.yaml`.
- `logs.collection_rate`: Rate (Bytes per second)at which logs read by collector
- `logs.sent_rate`: Rate (Bytes per second)at which logs sent by collector
- `logs.collector.cpu`: CPU usage for collector pods.
- `logs.collector.memory`: Memory usage for collector pods.
- `logs.collector.open_files`: No. of files open files.
- `logs.loki.events_sent`: Total number of events emitted to Loki
- `logs.loki.event_bytes_sent`: Total number of bytes emitted to Loki
- `logs.loki.distributor_lines_received`: Total number of lines received by Loki Distributor
- `logs.loki.distributor_ingester_appends`: Total number of appends to Ingester.
- `logs.loki.ingester_records_logged_rate`: Rate at which ingester updates WAL.
- …
> feat(SRVKP-6187): Loki & log Collector Metrics

- tests/scaling-pipelines/scenario/timebased-sign-pruner/locust/fetch-log.py
- tests/scaling-pipelines/scenario/timebased-sign-pruner/tierdown.sh
JIRA: https://issues.redhat.com/browse/SRVKP-7423
- Introduce new variable `LOCUST_WAIT_TIME` in timebased scenario test to control the wait time before starting locust test. (Default LOCUST_WAIT_TIME=600s) 
- `fetch-log.py` now selects the oldest taskrun record before making /log request.
> feat(SRVKP-7423): Locust wait time and Records sorting in Log Test

- ci-scripts/setup-cluster.sh
As per the latest [1.18 release](https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines/1.18/html/release_notes/op-release-notes#tekton-results-new-features-1-18_op-release-notes), Tekton Results is enabled by default. This seems to interfere with test execution in max-concurrency scenario. 
The PR disables the Tekton-Results during the cluster setup in the initialization phase.
> fix(SRVKP-7449): Disable Tekton-Results on cluster setup

- ci-scripts/lib.sh
- ci-scripts/setup-cluster.sh
This PR adds support to install Tekton Results from operator from 1.18 deployment version. Older version still use the default TektonResults CRD for setup.
https://issues.redhat.com/browse/SRVKP-7449
> feat(SRVKP-7449): Installing Tkn Results from Operator (1.18 onwards)

- ci-scripts/collect-results.sh
- ci-scripts/setup-cluster.sh
- Reworked on the Tekton Results disable logic to only apply it for v1.18 or above, since in the previous version the setting is not available in operator.
- Update SQL query for fetching empty record type.
> fix(SRVKP-7449): Disable results for Pipelines v1.18+
